name: mygesture
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.2
  fl_chart: ^0.40.0
  intl: ^0.17.0
  material_segmented_control: ^5.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  provider: ^6.1.1
  # Aggiungi qui la tua libreria GitHub
  flutterlibrary:
    git:
      url: https://github.com/Marcko1288/FlutterLibrary.git
  update: ^0.3.1

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - images/screen_login.png
